module.exports = {
    "prompts" : [
        { asked: false, ratedR: false, prompt: `Sing, O muse, of the _____ of Achilles.`},
        { asked: false, ratedR: false, prompt: `The worst subplot in a Jane Austen novel:`},
        { asked: false, ratedR: false, prompt: `Best acronym made from AHAB:`},
        { asked: false, ratedR: false, prompt: `Title of a book no one wants a movie made of:`},
        { asked: false, ratedR: false, prompt: `Worst Harry Potter sequel title:`},
        { asked: false, ratedR: false, prompt: `The disease that killed the martians in "The War of the Worlds:"`},
        { asked: false, ratedR: false, prompt: `If a goose laid golden eggs, what would a cow make?`},
        { asked: false, ratedR: false, prompt: `Name the protagonist of an unpublished cyberpunk novel:`},
        { asked: false, ratedR: false, prompt: `Name the protagonist of an unpublished YA fantasy novel:`},
        { asked: false, ratedR: false, prompt: `Name the protagonist of an unpublished Harlequin romance novel:`},
        { asked: false, ratedR: false, prompt: `Name the protagonist of an unpublished hard-boiled detective novel:`},
        { asked: false, ratedR: false, prompt: `You stepped on a butterfly while time-traveling. What rules the Earth on your return?`},
        { asked: false, ratedR: false, prompt: `Worst title for a diet & nutrition book?`},
        { asked: false, ratedR: false, prompt: `A mystery that not even Sherlock Holmes could solve:`},
        { asked: false, ratedR: false, prompt: `The title of a Romance novel starting genetically enhanced super-soldiers:`},
        { asked: false, ratedR: false, prompt: `Never trust an editor that says _____ is necessary.`},
        { asked: false, ratedR: false, prompt: `Joseph Campbell's "Hero with a Thousand _____."`},
        { asked: false, ratedR: false, prompt: `The Weirdest Grimm Fairy Tale:`},
        { asked: false, ratedR: false, prompt: `In order to succeed as a writer, you have to be willing to _____.`},
        { asked: false, ratedR: false, prompt: `From the writer of "David Don't" comes "Frances ______."`},
        { asked: false, ratedR: false, prompt: `Worst character to be in a mystery novel:`},
        { asked: false, ratedR: false, prompt: `Weirdest monster in the Odyssey:`},
        { asked: false, ratedR: false, prompt: `You're lured into a catacomb and then bricked in. What did Montresor use as bait?`},
        { asked: false, ratedR: false, prompt: `An inhabitant of Wonderland that Alice would run from:`},
        { asked: false, ratedR: false, prompt: `The opposite of 'Portal Fantasy' would be called:`},
        { asked: false, ratedR: false, prompt: `Most obvious killer in a mystery novel:`},
        { asked: false, ratedR: false, prompt: `Write the title for a romance title starring Bigfoot:`},
        { asked: false, ratedR: false, prompt: `Title for a YA coming-of-age book starring a duck:`},
        { asked: false, ratedR: false, prompt: `Worst animal companion for an adventure novel?`},
        { asked: false, ratedR: false, prompt: `"My beta-readers were super upset when they got to the ______ part of the story."`},
        { asked: false, ratedR: false, prompt: `A boring plot complication in a sci-fi novel:`},
        { asked: false, ratedR: false, prompt: `A new Teen Survival novel which is basically "The Hunger Games", but with _____.`},
        { asked: false, ratedR: false, prompt: `In most stories, the Whale is a metaphor for:`},
        { asked: false, ratedR: false, prompt: `Weirdest item to have to steal from a dragon's hoard?`},
        { asked: false, ratedR: false, prompt: `Dear reader, I _____ him.`},
        { asked: false, ratedR: false, prompt: `Worst thing to compare a summer's day to?`},
        { asked: false, ratedR: false, prompt: `The title of a "Self Improvement" book about farts:`},
        { asked: false, ratedR: false, prompt: `Dystopian fiction trope that became real:`},
        { asked: false, ratedR: false, prompt: `A charming story about a boy and his _____.`},
        { asked: false, ratedR: false, prompt: `Hardest animal to put down at the end of a YA coming-of-age story?`},
        { asked: false, ratedR: false, prompt: `A book with a dewey decimal number of 666:`},
        { asked: false, ratedR: false, prompt: `A book with a dewey decimal number of 069:`},
        { asked: false, ratedR: false, prompt: `If men are from mars and women from venus, where are children from?`},
        { asked: false, ratedR: false, prompt: `A pointless book to assign as summer reading:`},
        { asked: false, ratedR: false, prompt: `Coyote is an example of a(n) _____ archetype.`},
        { asked: false, ratedR: false, prompt: `Title a biography about President Lyndon Baines Johnson.`},
        { asked: false, ratedR: false, prompt: `A weird prank to play on Captain Ahab:`},
        { asked: false, ratedR: false, prompt: `For most epic fantasies, the story begins shortly after a ______ arrives at the village.`},
        { asked: false, ratedR: false, prompt: `A funny prank to play on Captain Hook:`},
        { asked: false, ratedR: false, prompt: `A fiction subgenre that should be a thing but isn't:`},
        { asked: false, ratedR: false, prompt: `A Cookbook you would never buy:`},
        { asked: false, ratedR: false, prompt: `A Cookbook you would immediately buy:`},
        { asked: false, ratedR: false, prompt: `"It was really weird when the magic merchant tried to trade me beans for my _____."`},
        { asked: false, ratedR: false, prompt: `Comma splace? More like comma _____.`},
        { asked: false, ratedR: false, prompt: `What's that stain on the cover of your favorite book?`},
        { asked: false, ratedR: false, prompt: `When you're at sea, you should absolutely not kill _____.`},
        { asked: false, ratedR: false, prompt: `A book you would not want to get from your grandmother:`},
        { asked: false, ratedR: false, prompt: `A Hogwarts house that was cut from the books:`},
        { asked: false, ratedR: false, prompt: `Name of a greek god who manages twitter:`},
        { asked: false, ratedR: false, prompt: `A book about bodily functions that you should not read your toddler:`},
        { asked: false, ratedR: false, prompt: `A book on relationships written by someone obviously horrible at them:`},
        { asked: false, ratedR: false, prompt: `You can't judge a book by its cover, but you can definitely judge it by its _____.`},
        { asked: false, ratedR: false, prompt: `A place for a pirate to store booty:`},
        { asked: false, ratedR: false, prompt: `How does James Patterson write so many books each year?`},
        { asked: false, ratedR: false, prompt: `Your protagonist is yanked back in time. What time period are they in?`},
        { asked: false, ratedR: false, prompt: `A cozy mystery series title based on a cat that frames bakers for crimes:`},
        { asked: false, ratedR: false, prompt: `An unauthorized use for bookmarks:`},
        { asked: false, ratedR: false, prompt: `What did they do with old physical card catalogs?`},
        { asked: false, ratedR: false, prompt: `A six word story:`},
        { asked: false, ratedR: false, prompt: `New from Stephen King: A horror story with a(n) _____ as an antagonist.`},
        { asked: false, ratedR: false, prompt: `A terrible name for a dragon:`},
        { asked: false, ratedR: false, prompt: `A diet book you can't wait to see exist:`},
        { asked: false, ratedR: false, prompt: `The best thing about being rejected from a publisher:`},
        { asked: false, ratedR: false, prompt: `Title of a picture book about trees:`},
        { asked: false, ratedR: false, prompt: `Title of a book about patriotic roads:`},
        { asked: false, ratedR: false, prompt: `Title of a historical novel about a loser:`},
        { asked: false, ratedR: false, prompt: `A cookbook about using unreasonable amounts of meat:`},
        { asked: false, ratedR: false, prompt: `What's the weirdest way for one of Coyote's pranks to backfire?`},
        { asked: false, ratedR: false, prompt: `How we know "Toad Hall" was definitely corrupt:`},
        { asked: false, ratedR: false, prompt: `From the author of "How Do Dinosaurs Clean Their Room?", "How Do Dinosaurs ______".`},
        { asked: false, ratedR: false, prompt: `Why exactly did "The Birds" decide to murder everyone?`},
        { asked: false, ratedR: false, prompt: `If living in a garden of poison made Rappaccini's daughter toxic, where did your mother grow up?`},
        { asked: false, ratedR: false, prompt: `Hemingway's unpublished final novel, a stirring tale of Man versus _____.`},
        { asked: false, ratedR: false, prompt: `Less well known than 'Common Sense' is Thomas Paine's other pamphlet: `},
        { asked: false, ratedR: false, prompt: `Weird thing to use as a bookmark:`},
        { asked: false, ratedR: false, prompt: `What do romance authors do after dark?`},
        { asked: false, ratedR: false, prompt: `Weird title for a science textbook:`},
        { asked: false, ratedR: false, prompt: `A sign that the librarian hates you:`},
        { asked: false, ratedR: false, prompt: `Victorian pulp authors used to get paid by the ______.`},
        { asked: false, ratedR: false, prompt: `What is the library hiding in the restricted section?`},
        { asked: false, ratedR: false, prompt: `Worst thing to find out from a FOIA inquiry:`},
        { asked: false, ratedR: false, prompt: `Why didn't Harper Lee ever release another novel?`},
        { asked: false, ratedR: false, prompt: `Who was the "Z" that F. Scott Fitzgerald dedicate his books to?`},
        { asked: false, ratedR: false, prompt: `Worst super-villain:`},
        { asked: false, ratedR: false, prompt: `Weirdest object to be the MacGuffin in a mystery novel about a theft:`},
        { asked: false, ratedR: false, prompt: `According to new research, whenever you're reading at least 10% of your brain is dedicated to _____.`},
        { asked: false, ratedR: false, prompt: `The worst thing to write a collectibles price guide for:`},
        { asked: false, ratedR: false, prompt: `A new thriller from author James Patterson: "_____"`},
        { asked: false, ratedR: false, prompt: `If there are 'Confederates in the Attic', where are the Neoconfederates?`},
        { asked: false, ratedR: false, prompt: `What is the story 'An Abundance of Katherines' really about?`},
        { asked: false, ratedR: false, prompt: `In addition to smarter older brother Mycroft, Sherlock Holmes also had an older sister who was better at ______.`},
        { asked: false, ratedR: false, prompt: `Name of a cookbook about eating people:`},
        { asked: false, ratedR: false, prompt: `What do Gonzo journalists usually do all day?`},
        { asked: false, ratedR: false, prompt: `When he died, Hunter S. Thompson demanded his ashes be fired from a cannon shaped like a _____.`},
        { asked: false, ratedR: false, prompt: `The first thing Charles Dickens would do if he came back from the dead:`},
        { asked: false, ratedR: false, prompt: `Name of a hero that just solves problems by sleeping with them:`},
        { asked: false, ratedR: false, prompt: `A great way to return library books:`},
        { asked: false, ratedR: false, prompt: `Worst audiobook narrator:`},
        { asked: false, ratedR: false, prompt: `Worst excuse trying get out of late return fees at a library:`},
        { asked: false, ratedR: false, prompt: `According to "Ends of the Earth," how did the dinosaurs really die out?`},
        { asked: false, ratedR: false, prompt: `A bad place to set a Sci-Fi story: the planet of ______.`},
        { asked: false, ratedR: false, prompt: `From a literary point of view, it's clear the Bible was written by _____.`},
        { asked: false, ratedR: false, prompt: `When writing a historical story set in the dark ages, it's important to remember:`},
        { asked: false, ratedR: false, prompt: `The title of a cookbook for dogs:`},
        { asked: false, ratedR: false, prompt: `A college course that would NOT require a textbook:`},
        { asked: false, ratedR: false, prompt: `Catchphrase of a Parrot that also solves mysteries:`},
        { asked: false, ratedR: false, prompt: `According to a new book, dinosaurs actually evolved into _____.`},
        { asked: false, ratedR: false, prompt: `A new Japanese light novel has the main character summoned to a different world and given the power to _____.`},
        { asked: false, ratedR: false, prompt: `A label on an object that Alice should DEFINITELY drink in Wonderland:`},
        { asked: false, ratedR: false, prompt: `Tired: Snow White and the 7 Dwarves. Wired: Snow White and the 7 _____.`},
        { asked: false, ratedR: false, prompt: `Tired: Children's Picture Books about Animals. Wired: Children's Picture Books about _____.`},
        { asked: false, ratedR: false, prompt: `When the aliens invaded, they came for Earth's _____.`},
        { asked: false, ratedR: false, prompt: `A really lame childhood trauma for the monster to be a metaphor for:`},
        { asked: false, ratedR: false, prompt: `What would you call a clone of Ernest Hemingway with lobster claws?`},
        { asked: false, ratedR: false, prompt: `Mary Shelly preserved her dead husband's _____ to remember him.`},
        { asked: false, ratedR: false, prompt: `It was a dark and stormy night. Then, the door slammed open! It was _____!!`},
        { asked: false, ratedR: false, prompt: `If dawn has "rose-red fingers" how would you describe night's hands?`},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: false, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
        // { asked: false, ratedR: true, prompt: ``},
    ]
}
